Moved quantity calculation to its own method `calculateTotalQuantity()`
customgento/CustomGento_ConfigurableTierPrices pull request #34
Opened 2018-03-29 13:36 UTC by shineability

- Moved quantity calculation to its own method `calculateTotalQuantity()`
- CS fixes

@sprankhub I removed the underscores from the protected functions (PSR-2), hope this is ok for you? Personally, I hate them, but I know it's still common practice in M1... Feel free to add them again :)

2018-04-05 13:41 UTC, shineability commented
@sprankhub Failed checks don't seem to be related to the actual tests. Can you have a look?

2018-04-05 14:57 UTC, sprankhub commented
Sorry that it takes so long, but since this is a critical change and involves background processes (new release, update on Marketplace etc.), we need some more time. I definitely have it on my list and will check this PR as soon as possible.

2018-05-14 06:42 UTC, sprankhub requested changes
Sorry for the late feedback. I had a quick look at it now and have to request a few changes. We will process the PR further once they are corrected. Thanks!

2018-05-14 06:42 UTC, sprankhub commented on app/code/community/CustomGento/ConfigurableTierPrices/Helper/Data.php
> -    // attribute code length must be less than 30 symbols!
Please keep this comment (as it is non-intuitive to use an abbreviated version of the extension name here).

2018-05-14 06:42 UTC, sprankhub commented on app/code/community/CustomGento/ConfigurableTierPrices/Helper/Data.php
> +        // Get the product attribute directly, because it may not be loaded
Please do not change such subtle things in a PR. It makes it harder to merge (and I prefer starting with lower case letters btw).

2018-05-14 06:42 UTC, sprankhub commented on app/code/community/CustomGento/ConfigurableTierPrices/Model/Observer.php
> +    protected $helper;
Please rename to `$_helper`.

2018-05-14 06:42 UTC, sprankhub commented on app/code/community/CustomGento/ConfigurableTierPrices/Model/Observer.php
> +    protected function calculateTierPrice($product)
Please rename to `_calculateTierPrice`.

2018-05-14 06:42 UTC, sprankhub commented on app/code/community/CustomGento/ConfigurableTierPrices/Model/Observer.php
> +    protected function calculateTotalQuantity($product)
Please rename to `_calculateTotalQuantity`.

2018-05-14 06:42 UTC, sprankhub commented on app/code/community/CustomGento/ConfigurableTierPrices/Model/Observer.php
> +    protected function getAllVisibleItems()
Please revert to `_getAllVisibleItems`.

2018-05-14 12:12 UTC, sprankhub commented
Thanks for the quick update! My colleague @norgeindian will further test and process this PR.

2018-05-15 07:22 UTC, merged

2018-05-15 08:26 UTC, shineability commented
@norgeindian Tnx!